# Generated by Django 4.2.6 on 2023-10-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='preference',
            field=models.IntegerField(choices=[(1, 'Not Interested'), (2, 'Maybe Later'), (3, 'Interested'), (4, 'Really Want It'), (5, 'Must Have')]),
        ),
    ]
