# Generated by Django 4.2.6 on 2023-10-25 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='like_scale',
            new_name='preference',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='goal',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
