<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-27 06:41

=======
# Generated by Django 4.2.6 on 2023-10-28 05:32

from django.conf import settings
>>>>>>> 46b58d208306ecb1a1dac7dd366c5b77b9330198
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('registerbook', '0002_auto_20231026_2228'),
=======
        ('registerbook', '0004_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 46b58d208306ecb1a1dac7dd366c5b77b9330198
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registerbook.book')),
=======
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_ordered', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registerbook.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 46b58d208306ecb1a1dac7dd366c5b77b9330198
            ],
        ),
    ]
