# Generated by Django 4.2.6 on 2023-10-27 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registerbook', '0002_auto_20231026_2228'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buybooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buybooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_ordered', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buybooks_user', to='registerbook.book')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registerbook.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buybooks_book', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
