# Generated by Django 4.2.6 on 2023-10-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buybooks', '0003_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buybooks',
            name='author',
        ),
    ]
