# Generated by Django 4.2.4 on 2023-10-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('B', 'Buyer')], default='B', max_length=1),
        ),
    ]
