# Generated by Django 4.2.6 on 2023-10-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
