# Generated by Django 4.2.4 on 2023-10-27 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('registerbook', '0002_auto_20231026_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='main.profile'),
            preserve_default=False,
        ),
    ]
