# Generated by Django 4.2.4 on 2023-12-14 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('registerbook', '0002_auto_20231029_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
    ]
