# Generated by Django 4.2.6 on 2023-10-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerbook', '0005_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
